name: Test trivy scan reusable workflow

on:
  push:
    branches:
      - 'trivy-scan'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git Hash (if not provided)
        id: get_hash
        run: echo "git_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Build and release 
        run: |
          docker build -t sample-flask:test-latest .

      - name: Set image repo output
        id: vars
        run: echo "image_repo=sample-flask:test-latest" >> $GITHUB_OUTPUT

      - name: Scan ${{ matrix.service }} image
        uses: ../.github/workflows/scan-build.yaml@trivy-scan
        with:
          image: ${{ steps.vars.outputs.image_repo }}
