name: Test trivy scan reusable workflow

on:
  push:
    branches:
      - 'trivy-scan'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set-image-name.outputs.image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git Hash (if not provided)
        id: get_hash
        run: echo "git_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Build and release
        run: |
          docker build -t sample-flask:test-latest .

      - name: Save Docker image as tar
        run: docker save -o sample-flask-test-latest.tar sample-flask:test-latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-flask-test-latest
          path: sample-flask-test-latest.tar

      - name: Set image name output
        id: set-image-name
        run: echo "image_name=sample-flask:test-latest" >> $GITHUB_OUTPUT

  scan:
    needs: build
    uses: amits2613/sample-flask/.github/workflows/scan-build.yaml@trivy-scan
    with:
      image: ${{ needs.build.outputs.image_name }}
      image_artifact: sample-flask-test-latest
